name: Publish Docker image

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: guillaumedorschner
  DOCKER_IMAGE_NAME: hackme

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
