name: Snyk Security Scan

on:
  workflow_dispatch

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run SAST (Static Code Analysis)
        run: snyk code test --severity-threshold=high

      - name: Run Dependency Vulnerability Scan
        run: snyk test --severity-threshold=high
